[env:esp32-s3-devkitc-1]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=3
monitor_speed = 115200
lib_deps =
  https://github.com/esp32beans/ESP32_USB_Host_HID/archive/e5cc02275155ddfa8a3d087a8094a865b5d07b17.zip
  dfrobot/DFRobot_DF1201S
  ncmreynolds/ld2410
  esp32async/AsyncTCP
  esp32async/ESPAsyncWebServer
